### ISSUE TITLE
Find db credentials in ENV[]

### ISSUE THREAD

**Issue by turadg** [customink/central_logger#8]
Is there a way to set the password now without including it in the source code?

How about a way to set authentication credentials through environmental variables?

**Comment by astupka** [comment]
Currently, there is no way to do either in the latest gem. The ENV check could be added around here, though.

https://github.com/customink/central_logger/blob/0.3.3/lib/central_logger/mongo_logger.rb#L138

**Comment by stevenkolstad** [comment]
It would be great to be able to use <%= ENV['MONGOHQ_URL'] %>

**Comment by turadg** [comment]
I forked this to try implementing the ENV search and discovered that the YAML loader runs through an ERB parser in the Rails.env. In other words, ENV values can be used as is by putting them in a .yml. E.g. for `central_logger.yml`:

```
production:
  database: system_log
  username: <%= ENV['CENTRAL_LOGGER_USERNAME'] %>
  password: <%= ENV['CENTRAL_LOGGER_PASSWORD'] %>
```

@agentrock, using `MONGOHQ_URL` is a little more work since you'd have to parse it, but it is possible to do in the YML with ERB. You could also try [this rejected patch for MONGOHQ_URL](https://github.com/peburrows/mongo_db_logger/pull/5).
